### ISSUE TITLE
MP3 detected as supported file

### ISSUE THREAD

**Issue by jonashaag** [erikd/libsndfile#610]
I have lots of errors like this when reading MP3 files using librosa:

```pytb
  File "/.../librosa/core/audio.py", line 157, in load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
  File ".../soundfile.py", line 860, in read
    frames = self._check_frames(frames, fill_value)
  File ".../soundfile.py", line 1268, in _check_frames
    raise ValueError("frames must be specified for non-seekable files")
ValueError: frames must be specified for non-seekable files
```

Unfortunately I cannot reproduce it reliably. 

Example file where it's broken: From Mozilla Common Voice, German corpus: common_voice_de_17324381.mp3 (attached). Also happens with other MP3 files.

Note that the `librosa.load` calls are done from Python threads (I use lots of threads).

Versions:

```
>>> soundfile.__version__
'0.10.2'
>>> soundfile.__libsndfile_version__
'1.0.29'
```

**Comment by jonashaag** [comment]
[common_voice_de_17324381.mp3.zip](https://github.com/erikd/libsndfile/files/5218359/common_voice_de_17324381.mp3.zip)

**Comment by jonashaag** [comment]
I also sometimes get this (with MP3 files)

```
Traceback (most recent call last):
  ...
  File "...librosa/core/audio.py", line 157, in load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
  File ".../soundfile.py", line 865, in read
    frames = self._array_io('read', out, frames)
  File ".../soundfile.py", line 1304, in _array_io
    raise ValueError("Invalid shape: {0!r}".format(array.shape))
ValueError: Invalid shape: (0,)
```

**Comment by jonashaag** [comment]
Yep, seems to be an issue with error reporting in threads. When using the following stress testing script, I also get the occasional `Not a valid SNDFILE* pointer`.

```py
import random
import soundfile as sf
import threading

# List of paths of MP3 files
files = open("/tmp/files").read().splitlines()

def func():
    for _ in range(1000):
        try:
            sf.read(random.choice(files))
        except Exception as e:
            if not "Format not recognised" in str(e):
                print(e)

threads = [threading.Thread(target=func) for _ in range(8)]
for t in threads:
    t.start()
for t in threads:
    t.join()
```

**Comment by evpobr** [comment]
Hi @jonashaag.

If you use Python library librosa, maybe it is better to create issue there? We're developing in C here, not Python.

**Comment by jonashaag** [comment]
Yeah maybe it is a problem with PySoundfile, but definitely not in librosa, as is evident from the latest code snippet I posted.

**Comment by jonashaag** [comment]
Ok, looks like it is the same issue as reported here: https://github.com/erikd/libsndfile/issues/279

Error variables not being thread safe. Is this something that you are willing to change in libsndfile (eg. by adding a new thread safe sf_open variant), or shall callers assume sf_open + error checking/reporting is not thread safe?

Btw here is the code I've used to debug this

```c
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sndfile.h>

#include "common.h"

static void
tryopen (const char *filename)
{
  SNDFILE    *file ;
  SF_INFO    sfinfo ;

  memset (&sfinfo, 0, sizeof (sfinfo)) ;

  if ((file = sf_open (filename, SFM_READ, &sfinfo)) == NULL)
  {  printf("Error is %d\n", sf_error(file));
    fflush (stdout) ;
    return ;
    } ;

  abort();

}

void *wrap (void *data) {
  for(int i=0; i<100; ++i)
    tryopen((char*)data);
}

int
main (int argc, char *argv [])
{
  static int nthreads = 12;
  pthread_t threads[nthreads];
  for (int i = 0; i < nthreads; ++i) {
    if(pthread_create(&threads[i], NULL, wrap,  (void*)argv[1])) {
      fprintf(stderr, "Error creating thread\n");
      return 1;
    }
  }
  for (int i = 0; i < nthreads; ++i) {
    if(pthread_join(threads[i], NULL)) {
      fprintf(stderr, "Error joining thread\n");
    }
  }
  return 0;
}
```

Output is a random sequence of these:

```
Error is 1
Error is 1
Error is 0
Error is 1
Error is 0
...
```

**Comment by evpobr** [comment]
Not in the foreseeable future.

**Comment by jonashaag** [comment]
Is this something you would be willing to review and merge if I contribute it?

**Comment by evpobr** [comment]
Let's see.

**Comment by jonashaag** [comment]
I wonder if there is anything that I did wrong to get such snippy responses from you. (They feel snippy to me at least.) It seems not to be your usual way of communicating here. If I did anything wrong, I am very sorry!

On the topic, would you mind to elaborate on "Let's see"? Do you mean that it depends? If so, depends on what?

**Comment by iaincoulter** [comment]
@jonashaag would be great if this was fixed,  currently in a multithreaded server application where you don't know when another thread is using sf_open/sf_error  we just return a generic error stating there was an issue but have no way of providing the exact cause as the error variables are not thread safe.
Never understood why #279 was marked as wont fix.

**Comment by jonashaag** [comment]
@evpobr any thoughts that you can share?

**Comment by evpobr** [comment]
> I wonder if there is anything that I did wrong to get such snippy responses from you. (They feel snippy to me at least.) It seems not to be your usual way of communicating here. If I did anything wrong, I am very sorry!
> 
> On the topic, would you mind to elaborate on "Let's see"? Do you mean that it depends? If so, depends on what?

Sorry, my english is bad 😄 

I mean - of cource i will be happy to review it.

**Comment by jonashaag** [comment]
Here are some of my ideas on how to fix it. Curious what you think about them.

- A) We change `sf_error` to be a thread local. Pros: simple; Cons: probably backwards incompatible?; not safe for concurrent open calls in the same thread.
- B) We add a new variant for any of the `sf_open*` variants that takes an optional `int *sf_error` pointer, where errors will be written to. Pros: simple; safe for concurrent open calls in the same thread; Cons: Grows API and code size (although we could use macros to autogenerate most of the code).
- C) Add optional, global (or thread-local), user-defined "error callback" that is called with the value of `sf_errno` each time it is changed. Pros: Backwards compatible; simple implementation; Cons: feels like a hack; probably not so simple to deal with as the library user.
- D) Variant of C) that doesn't use a callback but a `int *sf_error` instead. Not sure if that's possible at all, since the pointer target must be different for each thread (can thread locals work that way?)

**Comment by evpobr** [comment]
Why not guard all the reads/writes/ to `sf_errno`, `sf_parselog` and `sf_syserr`? Critical sections or something? There aren't many places where they are used.

**Comment by jonashaag** [comment]
It’s not a problem of non-atomic writes. The problem is that sf_errno is a global variable and context switches can happen between sf_errno is set (by the library) and read (by the user). For example thread A might open a file that can’t be opened, then context switch, then thread B successfully opens a file, then context switch, then thread A reads sf_errno which is 0 even though there was an error in thread A.

**Comment by evpobr** [comment]
So B is the only sane variant?

* No global variables
* Open functions return error code
* Any other functions must simply return `SFE_BAD_SNDFILE_PTR` if `SNDFILE` pointer is `NULL`
* Read/write must return zero at error
* No error reporting function (?)

**Comment by jonashaag** [comment]
By "return", you mean "write to user-specified pointer"? Otherwise, how would you "return" an error code from, say, `const char *sf_count_t sf_seek(...)` or `const char *sf_get_string(...)`?

What do you think about variant E)?

**Comment by evpobr** [comment]
I mean:

```
int sf_open2 (..., SNDFILE **sndfile) ;
```

**Comment by evpobr** [comment]
> What do you think about variant E)?

What is ths? `__thread` GCC extension?

**Comment by jonashaag** [comment]
I mean this https://en.m.wikipedia.org/wiki/Thread-local_storage

**Comment by evpobr** [comment]
This looks good. But there are so many variants if compiler doesn't support C11 threads.

**Comment by jonashaag** [comment]
That’s why I suggested variant E) where we add a new set of thread local error variables.

**Comment by evpobr** [comment]
> That’s why I suggested variant E) where we add a new set of thread local error variables.

Why not

```c
#ifdef HAVE_THREADS_H
#include <threads.h>
#endif

#ifndef thread_local
#elif defined __GNUC__ && __clang__
#define thread_local __thread
#elif defined _MSC_VER
#define thread_local __declspec(thread)
#else
#define thread_local
#endif
```

**Comment by evpobr** [comment]
> And if unsupported by the compiler, we can leave it out and thread safe error reporting is not available.

Another problem is how to find out that the library is built  using local thread safe globals before calling `sf_open`.

**Comment by jonashaag** [comment]
> Why not

Wouldn't this break backwards compatibility? Thread locals are stored differently than global variables; not sure if that could break anything?

> Another problem is how to find out that the library is built using local thread safe globals before calling `sf_open`.

That's easily solved by adding boolean valued routine to the API, right?

**Comment by evpobr** [comment]
> Wouldn't this break backwards compatibility? Thread locals are stored differently than global variables; not sure if that could break anything?

That worries me, too.

> That's easily solved by adding boolean valued routine to the API, right?

Yes, command interface.

**Comment by evpobr** [comment]
@jonashaag, change title of this issue please, it is confusing now.
